services:
    laravel.test:
        container_name: tu-ecommerce
        build:
            context: ./docker/production/8.3
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
                WWWUSER: '${WWWUSER}'
        image: sail-8.3/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: 'off'  # Deshabilitado en producción
            XDEBUG_CONFIG: ''
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - pgsql

    nginx:
        image: 'nginx:alpine'
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - '.:/var/www/html'
            - './docker/production/nginx/default.conf:/etc/nginx/conf.d/default.conf'
            - '/etc/letsencrypt:/etc/letsencrypt:ro'
        networks:
            - sail
        depends_on:
            - laravel.test

    pgsql:
        container_name: tu-ecommerce_pgsql
        image: 'postgres:15'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'sail-pgsql:/var/lib/postgresql/data'
            - './vendor/laravel/sail/database/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
        networks:
            sail:
                aliases:
                    - pgsql
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_DATABASE}'
                - '-U'
                - '${DB_USERNAME}'
            retries: 5
            timeout: 10s
        command: postgres -c ssl=off

networks:
    sail:
        driver: bridge

volumes:
    sail-pgsql:
        driver: local